backend:
  name: github
  repo: gosoares/cordeis
  branch: main
  squash_merges: true

publish_mode: editorial_workflow
site_url: "/"
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "cordeis"
    label: "Cordéis"
    folder: "content/cordeis"
    path: "{{slug}}/index"
    slug: "{{slug}}"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Date"
        name: "date"
        widget: "datetime"
        default: "{{now}}"
        date_format: "DD/MM/YYYY"

      - label: "Cover"
        name: "cover"
        widget: "object"
        fields:
          - label: "Image"
            name: "image"
            widget: "image"
            choose_url: false
            allow_multiple: false
            media_library:
              config:
                multiple: false
            media_folder: ""

      - label: "Body"
        name: "body"
        widget: "markdown"
