backend:
  name: test-repo

media_folder: "static/images/cordeis/{{slug}}" # Onde o widget 'image' salvará as imagens
public_folder: "/images/cordeis/{{slug}}" # Como o widget 'image' formará o URL

collections:
  - name: "cordeis"
    label: "Cordéis"
    folder: "content/cordeis"
    create: true
    path: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime", required: false }
      - label: "Capa" # Nome do campo no CMS para o objeto 'cover'
        name: "cover" # Nome da chave 'cover' no front matter
        widget: "object"
        required: false
        fields: # Sub-campos dentro do objeto 'cover'
          - { label: "Imagem da Capa", name: "image", widget: "image" }
          # Adicionar aqui outros sub-campos de 'cover' se necessário, como 'alt' ou 'caption'
      - { label: "Conteúdo", name: "body", widget: "markdown" }
